apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xcjiycz66-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xcjiycz66-go 
  name: xcjiycz66-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xcjiycz66-go 
